### ISSUE TITLE
User Login seems broken

### ISSUE THREAD

**Issue by SergioBitloops** [bitloops/frontend-copilot#1]
Something is happening with the login from the homepage. 

![Image](https://github.com/bitloops/frontend-copilot/assets/101190168/ffc6a9a3-e01b-4931-a5e5-98d419fc19f2)

![Image](https://github.com/bitloops/frontend-copilot/assets/101190168/9fce1fb9-6da7-44ab-ba5c-467fe0c2a125)

**Comment by danias** [comment]
Seems like a cashing issue.  Nothing to fix.
